version: '3.8'
services:
  valavid_webapp:
    container_name: valavid_webapp
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4769:3000'
    volumes:
      - /docker/projects/valavid/app/storage:/app/public/storage/