version: "3.1"
    services:
      nextjs:
        container_name: valavidfront
        command: next start
        ports:
          - 9011:3000
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - /app/node_modules
          - /app/.next
        restart: always
